#!/bin/bash


DIR1="/usr/bin/"
DIR2="/bin/"
DIR3="/home/woland/.local/bin/"

Menu="$(find "$DIR1" "$DIR2" "$DIR3" -executable | uniq -u | sort | fzf --prompt=" Run : " --border=rounded --margin=5% --height 100% --reverse --header=" PROGRAMS " --info=hidden --header-first)" 

devour "$Menu"
