#!/usr/bin/env bash

# Written by: Woland
# List PDFs in given directory and opens selection in Evince
# Dependency:
#           fd dmenu

search_dirs=("$HOME/Downloads/Documents" "$HOME/Documents")
declare -A file_paths

function findFiles(){
  while IFS= read -r file; do
    file_paths["$file"]=$(basename "$file")
  done < <(fd --type f --extension pdf --extension epub --extension djvu "" "${search_dirs[@]}")
}

function sendToDmenu(){
  if selection=$(printf '%s
    ' "${file_paths[@]}" | dmenu -p 'Library:' -l 15 -fn 'monospace-12' -nb '#282828' -nf '#fbf1c7' -sb '#458588' -sf '#000' -l 20); then
    for path in "${!file_paths[@]}"; do
      if [[ "${file_paths[$path]}" == "$selection" ]]; then
        zathura "$path"
        break
      fi
    done
  fi
}


function main(){
  findFiles
  sendToDmenu
}

main




















# Get terminal PPID and close terminal when the script is done
# PPPID=$(awk '{print $4}' "/proc/$PPID/stat")
# kill "$PPPID"

# book=$(find . -name "*.pdf" | dmenu -p "Select:")
# (( ${#book} > 0 )) && evince "$book" &
# evince "$book" & 
#====================
# Old Version, No FZF
#====================
# list=$(ls | grep -E '\.pdf$')

# PS3="Select Book: "
# select book in ${list}

#  do 
#      evince $book
#  done
